### ISSUE TITLE
Illegal State while comparing versions : [11.2.1.jre17] and [9.4.1.jre11]. Metadata = [null]

### ISSUE THREAD

**Issue by carolgschwend** [spring-projects-experimental/spring-boot-migrator#751] opened 2023-03-20 03:09 UTC
**Describe the bug**
Clicking on "Run Recipe" at http://localhost:8080/spring-boot-upgrade - 2.2.3. Remediation
throws Exception:

ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.sbm.engine.recipe.ActionFailedException: Action [OpenRewriteDeclarativeRecipeAdapter] 'Bump Spring Boot to 3.0.0' failed: java.lang.RuntimeException: org.openrewrite.UncaughtVisitorException: java.lang.IllegalStateException: Illegal State while comparing versions : [11.2.1.jre17] and [9.4.1.jre11]. Metadata = [null]] with root cause
java.lang.IllegalStateException: Illegal State while comparing versions : [11.2.1.jre17] and [9.4.1.jre11]. Metadata = [null]

**SBM Version**
v0.13.0

**SBM Application**
spring-boot-upgrade.jar

**To Reproduce**

1. run java -jar --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED spring-boot-upgrade.jar my_repo
2. open: http://localhost:8080/spring-boot-upgrade
3. click on 'Run Recipe' under 2.2.3. Remediation

**Expected behavior**
Expected it to apply recipe to my_repo.

**Screenshots**
![image](https://user-images.githubusercontent.com/21066111/226235988-357baabf-1c4e-424c-beb8-9936a64e5cf2.png)
![image](https://user-images.githubusercontent.com/21066111/226236569-932a8849-9a88-4b60-a9e0-c5f83cfeba85.png)

**Stacktrace**
ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.sbm.engine.recipe.ActionFailedException: Action [OpenRewriteDeclarativeRecipeAdapter] 'Bump Spring Boot to 3.0.0' failed: java.lang.RuntimeException: org.openrewrite.UncaughtVisitorException: java.lang.IllegalStateException: Illegal State while comparing versions : [11.2.1.jre17] and [9.4.1.jre11]. Metadata = [null]] with root cause
java.lang.IllegalStateException: Illegal State while comparing versions : [11.2.1.jre17] and [9.4.1.jre11]. Metadata = [null]
	at org.openrewrite.semver.LatestRelease.compare(LatestRelease.java:131)
	at org.openrewrite.maven.spring.UpgradeUnmanagedSpringProject$2.isVersionToUpgrade(UpgradeUnmanagedSpringProject.java:169)
	at org.openrewrite.maven.spring.UpgradeUnmanagedSpringProject$2.mayBeUpdateVersion(UpgradeUnmanagedSpringProject.java:145)
	at org.openrewrite.maven.spring.UpgradeUnmanagedSpringProject$2.visitTag(UpgradeUnmanagedSpringProject.java:131)
	at org.openrewrite.maven.spring.UpgradeUnmanagedSpringProject$2.visitTag(UpgradeUnmanagedSpringProject.java:116)
	at org.openrewrite.xml.tree.Xml$Tag.acceptXml(Xml.java:448)
	at org.openrewrite.xml.tree.Xml.accept(Xml.java:55)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
	at org.openrewrite.xml.XmlVisitor.lambda$visitTag$2(XmlVisitor.java:91)
	at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:141)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:123)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:141)
	at org.openrewrite.xml.XmlVisitor.visitTag(XmlVisitor.java:91)
	at org.openrewrite.maven.MavenIsoVisitor.visitTag(MavenIsoVisitor.java:38)
	at org.openrewrite.maven.spring.UpgradeUnmanagedSpringProject$2.visitTag(UpgradeUnmanagedSpringProject.java:119)
	at org.openrewrite.maven.spring.UpgradeUnmanagedSpringProject$2.visitTag(UpgradeUnmanagedSpringProject.java:116)
	at org.openrewrite.xml.tree.Xml$Tag.acceptXml(Xml.java:448)
	at org.openrewrite.xml.tree.Xml.accept(Xml.java:55)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
	at org.openrewrite.xml.XmlVisitor.lambda$visitTag$2(XmlVisitor.java:91)
	at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:141)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:123)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:141)
	at org.openrewrite.xml.XmlVisitor.visitTag(XmlVisitor.java:91)
	at org.openrewrite.maven.MavenIsoVisitor.visitTag(MavenIsoVisitor.java:38)
	at org.openrewrite.maven.spring.UpgradeUnmanagedSpringProject$2.visitTag(UpgradeUnmanagedSpringProject.java:119)
	at org.openrewrite.maven.spring.UpgradeUnmanagedSpringProject$2.visitTag(UpgradeUnmanagedSpringProject.java:116)
	at org.openrewrite.xml.tree.Xml$Tag.acceptXml(Xml.java:448)
	at org.openrewrite.xml.tree.Xml.accept(Xml.java:55)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
	at org.openrewrite.xml.XmlVisitor.visitDocument(XmlVisitor.java:71)
	at org.openrewrite.maven.MavenIsoVisitor.visitDocument(MavenIsoVisitor.java:23)
	at org.openrewrite.maven.MavenIsoVisitor.visitDocument(MavenIsoVisitor.java:20)
	at org.openrewrite.xml.tree.Xml$Document.acceptXml(Xml.java:173)
	at org.openrewrite.xml.tree.Xml.accept(Xml.java:55)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
	at org.openrewrite.RecipeScheduler.lambda$scheduleVisit$5(RecipeScheduler.java:241)
	at org.openrewrite.RecipeScheduler.lambda$mapAsync$0(RecipeScheduler.java:49)
	at org.openrewrite.scheduling.ForkJoinScheduler.lambda$schedule$0(ForkJoinScheduler.java:41)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Version 12.6.3

**Comment by fabapp2** [comment] 2023-10-11 08:28
Hi @carolgschwend thanks for reporting 🚀 
First of all please excuse my delayed reply.
````
org.openrewrite.maven.spring.UpgradeUnmanagedSpringProject$2.isVersionToUpgrade(UpgradeUnmanagedSpringProject.java:169)
````
makes me think the problem comes from the OpenRewrite recipe.
The OR version used in v0.13.0 is quite outdated and I'd hope the problem is gone when using the latest OR version, see #859.
It's been a while but if you could provide more details or maybe an example that reproduces the problem I'd add a test (and fix) as soon as the new `version/revamp` branch becomes the new `main`.
I'll close the issue for now. Please feel free to reopen it.

**Closed by fabapp2** 2023-10-11 08:28 UTC
Labels: type: bug
