### ISSUE TITLE
Scan throws ClassCastException: class org.openrewrite.java.tree.J$Case cannot be cast to class org.openrewrite.java.tree.Expression

### ISSUE THREAD

**Issue by fiveOO** [spring-projects-experimental/spring-boot-migrator#590] opened 2022-12-10 17:40 UTC
Scanning one module of a multi module project throws 
```
18:21:03.053 [main] ERROR o.s.s.o.RewriteExecutionContext - Exception occured!
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Case cannot be cast to class org.openrewrite.java.tree.Expression (org.openrewrite.java.tree.J$Case and org.openrewrite.java.tree.Expression are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @68f7aae2)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitVariables(ReloadableJava17ParserVisitor.java:1431)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitVariable(ReloadableJava17ParserVisitor.java:1346)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitVariable(ReloadableJava17ParserVisitor.java:71)
        at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1045)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convert(ReloadableJava17ParserVisitor.java:1482)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convert(ReloadableJava17ParserVisitor.java:1511)
...
```

Don't know if caused by the mentioned exception or by another cause: I've got some loggings like:
```
18:21:17.696 [main] ERROR o.s.s.j.impl.ProjectJavaSourcesImpl - Could not calculate if class 'org.openrewrite.java.tree.J$ClassDeclaration@ee8fe96b' implements an interface compatible to 'org.springframework.data.jpa.repository.JpaRepository'. Type of interface 'Xyz' could not be resolved and was 'Unknown'
```

Xyz is
- generated interface
- source located in target/generated-sources/openapi/restapi/...
- class located in target/classes/...
- source folder added to Maven compileSources by generator plugin (org.openapitools:openapi-generator-maven-plugin)

Win: 10
JDK: OpenJDK 64-Bit Server VM Zulu17.34+19-CA
SBM: 0.13.0

**Comment by fabapp2** [comment] 2022-12-15 13:13
I created #594

**Comment by fiveOO** [comment] 2022-12-15 13:39
After calling `mvn clean compile && xcopy /s target\generated-sources\openapi\restapi src\main\java` and scanning the `interface 'Xyz' could not be resolved` logs are gone but I still get the `ClassCastException` .

**Comment by fabapp2** [comment] 2022-12-17 09:49
@fiveOO could you provide a stacktrace including `org.springframework.sbm...` packages? I am guessing, but the CCE is not coming from `ProjectJavaSourcesImpl`? This seems to be "fixed" when generated sources get scanned (as expected) after copying them to `src`. 🤞

**Comment by fiveOO** [comment] 2022-12-17 12:39
Generated sources were copied to src/main/java.
Stacktrace at scanning is
```
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Case cannot be cast to class org.openrewrite.java.tree.Expression (org.openrewrite.java.tree.J$Case and org.openrewrite.java.tree.Expression are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @68f7aae2)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitVariables(ReloadableJava17ParserVisitor.java:1431)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitVariable(ReloadableJava17ParserVisitor.java:1346)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitVariable(ReloadableJava17ParserVisitor.java:71)
        at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1045)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convert(ReloadableJava17ParserVisitor.java:1482)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convert(ReloadableJava17ParserVisitor.java:1511)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convertStatements(ReloadableJava17ParserVisitor.java:1620)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convertStatements(ReloadableJava17ParserVisitor.java:1602)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitBlock(ReloadableJava17ParserVisitor.java:331)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitBlock(ReloadableJava17ParserVisitor.java:71)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1103)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convert(ReloadableJava17ParserVisitor.java:1482)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convertOrNull(ReloadableJava17ParserVisitor.java:1524)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitMethod(ReloadableJava17ParserVisitor.java:963)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitMethod(ReloadableJava17ParserVisitor.java:71)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:953)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convert(ReloadableJava17ParserVisitor.java:1482)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convert(ReloadableJava17ParserVisitor.java:1511)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convertStatements(ReloadableJava17ParserVisitor.java:1620)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convertStatements(ReloadableJava17ParserVisitor.java:1602)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitClass(ReloadableJava17ParserVisitor.java:472)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitClass(ReloadableJava17ParserVisitor.java:71)        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convert(ReloadableJava17ParserVisitor.java:1482)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convertAll(ReloadableJava17ParserVisitor.java:1535)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitCompilationUnit(ReloadableJava17ParserVisitor.java:518)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitCompilationUnit(ReloadableJava17ParserVisitor.java:71)
        at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:614)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
        at org.openrewrite.java.isolated.ReloadableJava17Parser.lambda$parseInputs$0(ReloadableJava17Parser.java:178)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputs(ReloadableJava17Parser.java:200)
        at org.openrewrite.java.Java17Parser.parseInputs(Java17Parser.java:43)
        at org.springframework.sbm.java.impl.RewriteJavaParser.parseInputs(RewriteJavaParser.java:61)
        at org.springframework.sbm.project.parser.MavenProjectParser.parseMainJavaSources(MavenProjectParser.java:217)
        at org.springframework.sbm.project.parser.MavenProjectParser.parse(MavenProjectParser.java:118)
        at org.springframework.sbm.project.parser.ProjectContextInitializer.initProjectContext(ProjectContextInitializer.java:53)
        at org.springframework.sbm.engine.commands.ScanCommand.execute(ScanCommand.java:57)
        at org.springframework.sbm.shell.ScanShellCommand.scan(ScanShellCommand.java:70)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.shell.command.invocation.InvocableShellMethod.doInvoke(InvocableShellMethod.java:306)
        at org.springframework.shell.command.invocation.InvocableShellMethod.invoke(InvocableShellMethod.java:232)
        at org.springframework.shell.command.CommandExecution$DefaultCommandExecution.evaluate(CommandExecution.java:158)
        at org.springframework.shell.Shell.evaluate(Shell.java:208)
        at org.springframework.shell.Shell.run(Shell.java:140)
        at org.springframework.shell.jline.InteractiveShellRunner.run(InteractiveShellRunner.java:73)
        at org.springframework.shell.DefaultShellApplicationRunner.run(DefaultShellApplicationRunner.java:65)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at org.springframework.sbm.SpringShellApplication.main(SpringShellApplication.java:27)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
```

**Comment by wkruse** [comment] 2023-03-15 15:52
@fiveOO: I was also getting the `java.lang.ClassCastException`, when running [v0.13.0](https://github.com/spring-projects-experimental/spring-boot-migrator/releases/tag/0.13.0). Building current `main` from source and running it fixed it for me.

**Comment by fabapp2** [comment] 2023-04-26 09:13
Closing this as it seems to be fixed, thanks @wkruse!
Analysing the stacktrace makes me think there was a problem with a Java class (which we don't have to reproduce) parsed by OpenRewrite.

**Closed by fabapp2** 2023-04-26 09:13 UTC
Labels: type: bug, in: engine
