### ISSUE TITLE
Scan step terminated with RootBuildFileNotFoundException

### ISSUE THREAD

**Issue by edigu** [spring-projects-experimental/spring-boot-migrator#830] opened 2023-06-27 15:52 UTC
**Describe the bug**
Hi! Today I wanted to give a try to SBM to upgrade a Spring boot 2.7.6 project to 3.0 release line and scanning immediately terminated with the stacktrace below.

I tried to run both `spring-boot-migrator.jar` and `spring-boot-upgrade.jar` and it seems the problem persists on both.

**SBM Version**
0.14.0

**SBM Application**
both shell and gui

**To Reproduce**
1. Go to cd ~/Projects
2. wget https://github.com/spring-projects-experimental/spring-boot-migrator/releases/download/0.14.0/spring-boot-migrator.jar
3. java -jar spring-boot-migrator.jar
4. scan my-boot2-project
5. See error

**Expected behavior**
Scanning finishes without errors, then I can apply the findings.

**Stacktrace**
```
migrator:> scan my-boot2-project

scanning 'my-boot2-project'

Checked preconditions for '/Users/me/src/Projects/my-boot2-project'
[ok] Found pom.xml.
[ok] 'sbm.gitSupportEnabled' is 'true', changes will be committed to branch [feature/upgrade] after each recipe.
[ok] Required Java version (17) was found.
[ok] Found required source dir 'src/main/java'.

Could not find BuildFile for root module.
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace

my-boot2-project:> stacktrace
org.springframework.sbm.build.api.RootBuildFileNotFoundException: Could not find BuildFile for root module.
	at org.springframework.sbm.build.api.RootBuildFileFilter.lambda$apply$2(RootBuildFileFilter.java:29)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.springframework.sbm.build.api.RootBuildFileFilter.apply(RootBuildFileFilter.java:29)
	at org.springframework.sbm.build.api.RootBuildFileFilter.apply(RootBuildFileFilter.java:21)
	at org.springframework.sbm.engine.context.ProjectContext.search(ProjectContext.java:94)
	at org.springframework.sbm.engine.context.ProjectContext.getBuildFile(ProjectContext.java:90)
	at org.springframework.sbm.build.migration.conditions.NoExactDependencyExist.evaluate(NoExactDependencyExist.java:40)
	at org.springframework.sbm.jee.jsf.conditions.IsMigrateJsf2ToSpringBootApplicableCondition.evaluate(IsMigrateJsf2ToSpringBootApplicableCondition.java:39)
	at org.springframework.sbm.engine.recipe.Recipe.isApplicable(Recipe.java:92)
	at org.springframework.sbm.engine.recipe.Recipes.lambda$getApplicable$2(Recipes.java:50)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.springframework.sbm.engine.recipe.Recipes.getApplicable(Recipes.java:51)
	at org.springframework.sbm.engine.commands.ApplicableRecipeListCommand.getApplicableRecipes(ApplicableRecipeListCommand.java:48)
	at org.springframework.sbm.engine.commands.ApplicableRecipeListCommand.execute(ApplicableRecipeListCommand.java:42)
	at org.springframework.sbm.shell.ScanShellCommand.scan(ScanShellCommand.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.shell.command.invocation.InvocableShellMethod.doInvoke(InvocableShellMethod.java:306)
	at org.springframework.shell.command.invocation.InvocableShellMethod.invoke(InvocableShellMethod.java:232)
	at org.springframework.shell.command.CommandExecution$DefaultCommandExecution.evaluate(CommandExecution.java:160)
	at org.springframework.shell.Shell.evaluate(Shell.java:208)
	at org.springframework.shell.Shell.run(Shell.java:140)
	at org.springframework.shell.jline.InteractiveShellRunner.run(InteractiveShellRunner.java:73)
	at org.springframework.shell.DefaultShellApplicationRunner.run(DefaultShellApplicationRunner.java:65)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at org.springframework.sbm.SpringShellApplication.main(SpringShellApplication.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)

```
The project has the standard spring boot layout with pom.xml that is generated at start.spring.io. It does not have a multi-module setup.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Version 12.6.6
 - Java version: openjdk "17.0.5" 2022-10-18
 - JDK:  OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)

**Comment by fabapp2** [comment] 2023-06-29 20:36
Thanks for reporting @edigu 🚀 

I tried, but I couldn't reproduce the problem.

1. Created a project from start.spring.io [issue-830.zip](https://github.com/spring-projects-experimental/spring-boot-migrator/files/11910299/issue-830.zip)
2. Started 0.14.0 and scanned and it listed applicable recipes.

I am wondering how this happens as the precondition check found a file named `pom.xml` but the `RootBuildFileFilter` 
couldn't find the pom as `BuildFile` representation, which is strange.
However, I can't reproduce this issue. Could you please provide a minimalistic project, you mentioned you have a dummy project?

**Comment by fabapp2** [comment] 2023-06-29 20:40
I will close this for now. 
Please just reopen this issue if it still persists and you can provide an example to reproduce the problem.

**Closed by fabapp2** 2023-06-29 20:40 UTC
Labels: type: bug, status: can't reproduce
