### ISSUE TITLE
Issues when scanning an application on a different drive under Windows

### ISSUE THREAD

**Issue by Richhoef** [spring-projects-experimental/spring-boot-migrator#495] opened 2022-10-21 09:28 UTC
labels: ["type: bug","wontfix","to_archive"]

**Describe the bug**
Whenever I scan a project, the preconditionCheck fails. It cannot find the maven build file and it also cannot find a 'src/main/java' directory, while this does exists. I am using a Windows 10 pc with Java 17.0.5 and SBM 0.12.0. 

**To Reproduce**
1. Unpack the repository TestMigrator ([TestMigrator.zip](https://github.com/spring-projects-experimental/spring-boot-migrator/files/9837612/TestMigrator.zip))
2. Start SBM
3. Type `scan D:\\TestMigrator`
4. Observe the failure
![image](https://user-images.githubusercontent.com/51912545/197162713-5e9b0708-5edf-4bc3-855a-46ca2878f920.png)

**Expected behavior**
A pass of the maven build file (a pom.xml is present)
A pass of the 'src/main/java' dir (which also exists)

**Desktop:**
 - OS: Windows
 - Version 10 21H2
 - Java 17.0.5

**Comment by fabapp2** [comment] 2022-10-31 22:59
Hi @Richhoef 

thank you for reporting this 🚀  
...and sorry for my late reply, I was on vacation.

I need to run this on Windows as I think that's the reason and something broke without notice as we're on Mac in our team.
I will look into it.

**Comment by fabapp2** [comment] 2022-11-07 12:06
Hi @Richhoef 

We couldn't reproduce the problem using the correct path which for the provided demo application is 
`scan C:\\TestMigrator\\TestMigrator`. 
After adding it to Git it scanned without any problems and offered us applicable recipes too.
I'm closing this issue now. If the problem persists please create a new ticket or reopen this one.

**Comment by Richhoef** [comment] 2022-11-07 14:05
@fabapp2 Thanks a lot for trying your best! For some weird reason I cannot reproduce this anymore. So even for me, this issue is solved now! Curious what the issue was and why it is fixed now, but happy it is working as intended (maybe because of a pc reboot or something like that).

**Comment by fabapp2** [comment] 2022-11-07 14:57
@Richhoef that's great news! Glad it works so far. Please don't hesitate to add more issues in case you face other problems.

**Comment by BWagener** [comment] 2022-11-24 15:19
Hello @Richhoef @fabapp2,

I ran into this exact issue on windows. I was able to get around it by moving the the jar of the migrator to the drive where the code was.
I can reproduce it by moving the jar back to another drive.

Cheers

**Comment by fabapp2** [comment] 2022-11-25 09:48
Hi @BWagener,

thanks for reporting. 
I will give it a try (if my VDI lets me create a new drive) and report back here.

**Comment by Richhoef** [comment] 2022-11-26 09:41
@BWagener, well that explains a lot! 
That is exactly the difference between the first try (which failed) and the second try a few days later, now I think of it. Thanks for clearing this up!

**Closed** 2023-08-31 09:50 UTC
Labels: type: bug, wontfix, to_archive
