### ISSUE TITLE
Null pointer exception when scanning

### ISSUE THREAD

**Issue by pgovindraj** [spring-projects-experimental/spring-boot-migrator#605] opened 2023-01-01 02:00 UTC
When scanning a source code with spring boot migrator, I get a NPE. The stacktrace is given below:

> [ok] Found pom.xml.
> 
> [ok] 'sbm.gitSupportEnabled' is 'false', Nothing will be committed.
> [ok] Required Java version (17) was found.
> [ok] Found required source dir 'src/main/java'.
> 
> 
> Maven        100% │████████████████████████████████│ 48/48 (0:00:53 / 0:00:00)
> This could be a broken jar. Activate logging on WARN level for 'org.openrewrite' might reveal more information.
> Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
> migrator:> stacktrace
> java.lang.RuntimeException: This could be a broken jar. Activate logging on WARN level for 'org.openrewrite' might reveal more information.
> 	at org.springframework.sbm.openrewrite.RewriteExecutionContext.lambda$createErrorHandler$0(RewriteExecutionContext.java:58)
> 	at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputsToCompilerAst(ReloadableJava17Parser.java:270)
> 	at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputs(ReloadableJava17Parser.java:161)
> 	at org.openrewrite.java.Java17Parser.parseInputs(Java17Parser.java:43)
> 	at org.springframework.sbm.java.impl.RewriteJavaParser.parseInputs(RewriteJavaParser.java:61)
> 	at org.springframework.sbm.project.parser.MavenProjectParser.parseMainJavaSources(MavenProjectParser.java:217)
> 	at org.springframework.sbm.project.parser.MavenProjectParser.parse(MavenProjectParser.java:118)
> 	at org.springframework.sbm.project.parser.ProjectContextInitializer.initProjectContext(ProjectContextInitializer.java:53)
> 	at org.springframework.sbm.engine.commands.ScanCommand.execute(ScanCommand.java:57)
> 	at org.springframework.sbm.shell.ScanShellCommand.scan(ScanShellCommand.java:70)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.springframework.shell.command.invocation.InvocableShellMethod.doInvoke(InvocableShellMethod.java:306)
> 	at org.springframework.shell.command.invocation.InvocableShellMethod.invoke(InvocableShellMethod.java:232)
> 	at org.springframework.shell.command.CommandExecution$DefaultCommandExecution.evaluate(CommandExecution.java:158)
> 	at org.springframework.shell.Shell.evaluate(Shell.java:208)
> 	at org.springframework.shell.Shell.run(Shell.java:140)
> 	at org.springframework.shell.jline.InteractiveShellRunner.run(InteractiveShellRunner.java:73)
> 	at org.springframework.shell.DefaultShellApplicationRunner.run(DefaultShellApplicationRunner.java:65)
> 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
> 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
> 	at org.springframework.sbm.SpringShellApplication.main(SpringShellApplication.java:27)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
> 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
> Caused by: org.openrewrite.java.JavaParsingException: Failed symbol entering or attribution
> 	... 34 more
> Caused by: java.lang.NullPointerException: Cannot read field "info" because "lintEnv" is null
> 	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5340)
> 	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5200)
> 	at com.sun.tools.javac.comp.Attr.attrib(Attr.java:5145)
> 	at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1317)
> 	at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1290)
> 	at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputsToCompilerAst(ReloadableJava17Parser.java:266)
> 	... 33 more`

This issue seems to be similar to #467, but a supported JDK is being used here:

openjdk version "17.0.4.1" 2022-08-12 LTS
OpenJDK Runtime Environment Zulu17.36+17-CA (build 17.0.4.1+1-LTS) 
OpenJDK 64-Bit Server VM Zulu17.36+17-CA (build 17.0.4.1+1-LTS, mixed mode, sharing)

**Comment by fabapp2** [comment] 2023-01-03 13:55
Hi @pgovindraj 
thanks for reporting 🚀 

>Caused by: java.lang.NullPointerException: Cannot read field "info" because "lintEnv" is null

makes me think that something does not work with the given JDK, even so, you're using a version supported by OpenRewrite. OR is accessing JDK internals for their magic and the error makes me think `info` can't be accessed in the given JDK (for whatever reason). 

I will need to try the exact same JDK to hopefully be able to reproduce.
In the meantime you might try another JDK, I am using ?´OpenJDK 64-Bit Server VM Zulu17.32+13-CA (build 17.0.2+8-LTS, mixed mode, sharing) where I didn't see this error so far. I am wondering if it gets more interesting than that as our JDKs are pretty similar 🤔 

I will ping you as soon as I made any progress on this.

**Comment by fabapp2** [comment] 2023-01-03 13:56
@tkvangorder have you seen this? Is my assumption correct or do you have any other ideas?

**Comment by fabapp2** [comment] 2023-01-03 17:35
@pgovindraj could you please try again logging on WARN level for `org.openrewrite`?
I had a similar issue just now because of a broken jar. Just to be sure that this isn't the case here. If this is the case deleting `~/.rewrite/cache/artifacts` and the broken jar in `~/.m2/repository` and retrying should solve this issue. At least if it's downloaded in a non-broken state then. 
Please let me know if this solved the issue for you.

**Comment by pathjava** [comment] 2023-04-09 14:58
@pgovindraj 
```
[ok] Found pom.xml.
[ok] 'sbm.gitSupportEnabled' is 'true', changes will be committed to branch [develop] after each recipe.
[ok] Required Java version (17) was found.
[ok] Found required source dir 'src/main/java'.
```
I have the same problem. At first everything is successful, and then an error. I am using JDK17.0.6.
Your advice did not help solve the problem.

```
java.lang.RuntimeException: This could be a broken jar. Activate logging on WARN level for 'org.openrewrite' might reveal more information.
        at org.springframework.sbm.openrewrite.RewriteExecutionContext.lambda$createErrorHandler$0(RewriteExecutionContext.java:58)
        at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputsToCompilerAst(ReloadableJava17Parser.java:270)
        at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputs(ReloadableJava17Parser.java:161)
        at org.openrewrite.java.Java17Parser.parseInputs(Java17Parser.java:43)
        at org.springframework.sbm.java.impl.RewriteJavaParser.parseInputs(RewriteJavaParser.java:61)
        at org.springframework.sbm.project.parser.MavenProjectParser.parseTestJavaSources(MavenProjectParser.java:193)
        at org.springframework.sbm.project.parser.MavenProjectParser.parse(MavenProjectParser.java:149)
        at org.springframework.sbm.project.parser.ProjectContextInitializer.initProjectContext(ProjectContextInitializer.java:53)
        at org.springframework.sbm.engine.commands.ScanCommand.execute(ScanCommand.java:57)
        at org.springframework.sbm.shell.ScanShellCommand.scan(ScanShellCommand.java:70)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.shell.command.invocation.InvocableShellMethod.doInvoke(InvocableShellMethod.java:306)
        at org.springframework.shell.command.invocation.InvocableShellMethod.invoke(InvocableShellMethod.java:232)
        at org.springframework.shell.command.CommandExecution$DefaultCommandExecution.evaluate(CommandExecution.java:158)
        at org.springframework.shell.Shell.evaluate(Shell.java:208)
        at org.springframework.shell.Shell.run(Shell.java:140)
        at org.springframework.shell.jline.InteractiveShellRunner.run(InteractiveShellRunner.java:73)
        at org.springframework.shell.DefaultShellApplicationRunner.run(DefaultShellApplicationRunner.java:65)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at org.springframework.sbm.SpringShellApplication.main(SpringShellApplication.java:27)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.openrewrite.java.JavaParsingException: Failed symbol entering or attribution
        ... 34 more
Caused by: java.lang.NullPointerException: Cannot read field "info" because "lintEnv" is null
        at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5340)
        at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5200)
        at com.sun.tools.javac.comp.Attr.attrib(Attr.java:5145)
        at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1317)
        at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1290)
        at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputsToCompilerAst(ReloadableJava17Parser.java:266)
        ... 33 more
```

**Comment by pathjava** [comment] 2023-04-10 05:41
Hi @pgovindraj. Have you resolved this issue?

**Comment by pgovindraj** [comment] 2023-04-10 06:38
Unfortunately, the issues is still there @pathjava

**Comment by victor-denisenko** [comment] 2023-04-12 19:46
> @pgovindraj could you please try again logging on WARN level for `org.openrewrite`? I had a similar issue just now because of a broken jar. Just to be sure that this isn't the case here. If this is the case deleting `~/.rewrite/cache/artifacts` and the broken jar in `~/.m2/repository` and retrying should solve this issue. At least if it's downloaded in a non-broken state then. Please let me know if this solved the issue for you.

Thanks, this worked for me. I had the same error, but after deleting the `%USERPROFILE%/.rewrite` folder completely, it works as expected with `openjdk-17.0.2`.


I'm not sure if this can help, but I ran `spring-boot-migrator.jar` with changed `application.properties` :
```
spring.profiles.active=default, core
spring.application.name=spring-boot-migrator
# toggle support for git to sync and auto-commit
sbm.gitSupportEnabled=false
sbm.muleTriggerMeshTransformEnabled=false
logging.level.org=WARN
logging.level.org.springframework.sbm.logging.MethodCallTraceInterceptor=DEBUG
logging.level.org.springframework.sbm.logging.StopWatchTraceInterceptor=DEBUG
logging.level.org.springframework=WARN
logging.level.org.openrewrite=WARN
logging.level.org.springframework.sbm=WARN
```

**Comment by fabapp2** [comment] 2023-04-26 09:46
Thank you for trying and reporting @victor-denisenko, @pgovindraj, @pathjava! 🚀 
Defining `org.openrewrite` on warn would be quite noisy?
 I am hoping that there will be less broken downloads with later versions of OR.
 
 Closing this as we can't do anything.

**Closed by fabapp2** 2023-04-26 09:46 UTC
Labels: type: bug
