### ISSUE TITLE
No version provided for dependency org.twitter4j:twitter4j-core

### ISSUE THREAD

**Issue by sydneyhenrard** [spring-projects-experimental/spring-boot-migrator#727] opened 2023-02-17 20:16 UTC
After running the `scan` command of `spring-boot-migrator.jar`, I get an error about maven parsing
```
No version provided for dependency org.twitter4j:twitter4j-core
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.

migrator:> stacktrace
org.openrewrite.maven.internal.MavenParsingException: No version provided for dependency org.twitter4j:twitter4j-core
        at org.openrewrite.maven.tree.ResolvedPom.resolveDependencies(ResolvedPom.java:525)
        at org.openrewrite.maven.tree.ResolvedPom.resolveDependencies(ResolvedPom.java:499)
        at org.openrewrite.maven.tree.MavenResolutionResult.resolveDependencies(MavenResolutionResult.java:159)
```

**pom.xml**
```
<properties>
    <twitter4j.version>4.0.7</twitter4j.version>
<properties>

<dependencies>
    <dependency>
        <groupId>org.twitter4j</groupId>
        <artifactId>twitter4j-core</artifactId>
        <version>${twitter4j.version}</version>
    </dependency>
</dependencies>
```
Spring Boot 2.7.2
Java 17

**Comment by fabapp2** [comment] 2023-02-21 03:55
Probably a typo, but could you try closing `</properties>`?
Parsing a minimal pom.xml with the given property and dependency worked in a test.
Could you provide an example and reopen the issue? 
Closing this, for now, can't reproduce it.

**Closed by fabapp2** 2023-02-21 03:55 UTC

**Comment by sydneyhenrard** [comment] 2023-02-21 18:18
Found the issue, I had other pom.xml in other subfolders. After removing these unnecessary subfolders, it's working. You can see 14/14 because I have 7 pom.xml.
```
Maven        100% │████████████████████████████████│ 14/14 (0:00:01 / 0:00:00) No version provided for dependency org.twitter4j:twitter4j-core
```
After cleanup
```
Maven        100% │██████████████████████████████████│ 2/2 (0:00:00 / 0:00:00)
```
I still get an Exception but I managed to apply a recipe
```
19:16:44.918 [main] ERROR o.s.s.o.RewriteExecutionContext - Exception occured!
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Case cannot be cast to class org.openrewrite.java.tree.Expression (org.openrewrite.java.tree.J$Case and org.openrewrite.java.tree.Expression are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @2f410acf)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitAssignment(ReloadableJava17ParserVisitor.java:214)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitAssignment(ReloadableJava17ParserVisitor.java:71)
        at com.sun.tools.javac.tree.JCTree$JCAssign.accept(JCTree.java:2051)
```

**Comment by fabapp2** [comment] 2023-06-13 08:09
Hi @sydneyhenrard 
Sorry for my (very) late reply. Happy you solved the issue. Did the recipe run successfully regardless of the exception?
Could you maybe provide a stacktrace and open a new issue?
